classroom/urls.py
from django.urls import path
from .views import (HomeView, ThankYouView, ContactFormView,
                    TeacherCreateView, TeacherListView, TeacherDetailView,
                    TeacherUpdateView, TeacherDeleteView)
app_name = 'classroom'

urlpatterns = [
    path('', HomeView.as_view(), name='home'),
    path('thank_you/', ThankYouView.as_view(), name='thank_you'),
    path('contact/', ContactFormView.as_view(), name='contact'),
    path('create_teacher/', TeacherCreateView.as_view(), name='create_teacher'),
    path('list_teacher/', TeacherListView.as_view(), name='list_teacher'),
    path('teacher_detail/<int:pk>',
         TeacherDetailView.as_view(), name='detail_teacher'),
    path('update_teacher/<int:pk>',
         TeacherUpdateView.as_view(), name='update_teacher'),
    path('delete_teacher/<int:pk>',
         TeacherDeleteView.as_view()),
]

school/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('accounts/', include('django.contrib.auth.urls')),
    path('admin/', admin.site.urls),
    path('', include('classroom.urls')),

]

accounts/models.py
from django.db import models

# Create your models here.

classroom/models.py
from django.db import models

# Create your models here.


class Teacher(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    subject = models.CharField(max_length=30)

    def __str__(self):
        return f"{self.first_name} {self.last_name} teaches {self.subject}"

classroom/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

accounts/views.py
from django.shortcuts import render

# Create your views here.

classroom/views.py
from django.shortcuts import render
from django.views.generic import (
    TemplateView, FormView, CreateView, ListView, DetailView, UpdateView, DeleteView)
from . forms import ContactForm
from . models import Teacher
from django.urls import reverse_lazy
# Create your views here.


class HomeView(TemplateView):
    template_name = 'classroom/home.html'


class ContactFormView(FormView):
    form_class = ContactForm
    template_name = 'classroom/contact.html'
    success_url = reverse_lazy('classroom:thank_you')

    def form_valid(self, form):
        print(form.cleaned_data)
        return super().form_valid(form)


class TeacherCreateView(CreateView):
    model = Teacher
    fields = "__all__"
    success_url = reverse_lazy('classroom:list_teacher')
    # modelname_form.html === teacher_form.html


class TeacherListView(ListView):
    model = Teacher
    context_object_name = 'teacher_list'
    queryset = Teacher.objects.order_by("first_name")
    # modelname_list.html === teacher.list.html


class TeacherDetailView(DetailView):
    model = Teacher
    # modelname_detail.html === teacher_detail.html


class TeacherUpdateView(UpdateView):
    model = Teacher
    fields = "__all__"
    success_url = reverse_lazy('classroom:list_teacher')


class TeacherDeleteView(DeleteView):
    model = Teacher
    success_url = reverse_lazy('classroom:list_teacher')
    # modelname_confirm_delete.html


class ThankYouView(TemplateView):
    template_name = 'classroom/thank_you.html'

classroom/templates/classroom/contact.html
<h1>Form View</h1>

<form method="POST">
  {% csrf_token %} {{form.as_p}}
  <input type="submit" value="Submit" />
</form>

<ul>
  <li>
    <a href="{% url 'classroom:home' %}">Home Page</a>
  </li>
</ul>

classroom/templates/classroom/home.html
<h1>Hello From Home Page</h1>

<ul>
  <li>
    <a href="{% url 'classroom:thank_you' %}">Thank You Page</a>
  </li>
  <li>
    <a href="{% url 'classroom:contact' %}">Contact Page</a>
  </li>
  <li>
    <a href="{% url 'classroom:create_teacher' %}">Create New Teacher Page</a>
  </li>
  <li>
    <a href="{% url 'classroom:list_teacher' %}">Teacher List Page</a>
  </li>
</ul>

classroom/templates/classroom/teacher_confirm_delete.html
<!-- <h1>Are You sure you want to delete</h1>
{{form}}
<form method="POST">
    {% csrf_token %}
</form>
<input type="submit" value="Cofirm Delete"/> -->

<form method="POST">{% csrf_token %}

    <p>Are you sure you want to delete "{{ object }}"?</p>

        <input type="submit" value="Confirm">
</form>

classroom/templates/classroom/teacher_detail.html
<h1>Teacher Detail View</h1>
{{teacher}}

<ul>
  <li>
    <a href="{% url 'classroom:home' %}">Home Page</a>
  </li>
</ul>

classroom/templates/classroom/teacher_form.html
<h1>Teacher Form</h1>

<form method="POST">
  {% csrf_token %} {{form.as_p}}
  <input type="submit" value="Submit" />
</form>

classroom/templates/classroom/teacher_list.html
<h1>Teacher List View</h1>

<ul>
  {% for teacher in teacher_list %}
  <li>
    <a href="/teacher_detail/{{teacher.id}}"
      >{{teacher.first_name}} {{teacher.last_name}}</a
    >
    <ul>
      <li>
        <a href="/update_teacher/{{teacher.id}}"
          >Update Info for {{teacher.first_name}}</a
        >
      </li>
      <li>
        <a href="/delete_teacher/{{teacher.id}}">
          Delete {{teacher.first_name}}</a
        >
      </li>
    </ul>
  </li>
  {% endfor %}
</ul>

<ul>
  <li>
    <a href="{% url 'classroom:home' %}">Home Page</a>
  </li>
</ul>

classroom/templates/classroom/thank_you.html
<h1>Thank You</h1>
<ul>
  <li>
    <a href="{% url 'classroom:home' %}">Home Page</a>
  </li>
</ul>

templates/base_generic.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
  </head>
  <body>
    <div>{% block content %} {% endblock %}</div>
  </body>
</html>

{% comment %}
<ul class="sidebar-nav">
  … {% if user.is_authenticated %}
  <li>User: {{ user.get_username }}</li>
  <li><a href="{% url 'logout' %}?next={{ request.path }}">Logout</a></li>
  {% else %}
  <li><a href="{% url 'login' %}?next={{ request.path }}">Login</a></li>
  {% endif %}
</ul>
{% endcomment %}